version: 2

registries:
  github-packages:
    type: nuget-feed
    url: https://nuget.pkg.github.com/ParagRaut/index.json
    username: ParagRaut
    token: ${{secrets.DEPENDABOT_GITHUB_PACKAGES_TOKEN}}

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - github-packages
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
